name: Fetch Latest Wikidata Mappings

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Fetch Data from Wikidata
        run: python fetch_wikidata.py

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update Wikidata movie and TV mappings (CSV)"
          file_pattern: "data/movie_mappings.csv data/tv_mappings.csv" 
          commit_user_name: "Wikidata Bot [GH Action]"
          commit_user_email: "actions@github.com"
          commit_author: "Wikidata Bot <actions@github.com>"